name: mobile
description: "A mobile tap arcade game that tests users' coordination skills."
publish_to: "none"

version: 2.0.0+2024110701

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  collection: ^1.18.0                             # https://pub.dev/packages/collection (Dart)
  confetti: ^0.7.0                                # https://pub.dev/packages/confetti (verified)
  device_info_plus: ^10.1.2                       # https://pub.dev/packages/device_info_plus (verified)
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  flame: ^1.13.1                                  # https://pub.dev/packages/flame (Flame Engine)
  flame_audio: ^2.10.3                            # https://pub.dev/packages/flame_audio (verified)
  flutter_fgbg: ^0.6.0                            # https://pub.dev/packages/flutter_fgbg

  # TODO: Remove when https://github.com/dart-lang/build/issues/3745 is fixed.
  frontend_server_client: ^4.0.0

  google_fonts: ^6.2.1                            # https://pub.dev/packages/google_fonts (verified)
  google_mobile_ads: ^5.1.0
  http: ^1.2.2                                    # https://pub.dev/packages/http (Dart)
  in_app_review: ^2.0.9                           # https://pub.dev/packages/in_app_review (verified)
  internet_connection_checker_plus: ^2.5.1        # https://pub.dev/packages/internet_connection_checker_plus/changelog (verified)
  package_info_plus: ^8.0.2                       # https://pub.dev/packages/package_info_plus (verified)
  purchases_flutter: ^8.1.0                       # https://pub.dev/packages/purchases_flutter (verified)
  quiver: ^3.2.2                                  # https://pub.dev/packages/quiver
  shared_preferences: ^2.2.2                      # https://pub.dev/packages/shared_preferences (Flutter)
  url_launcher: ^6.2.4                            # https://pub.dev/packages/url_launcher (Flutter)
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  build_runner: ^2.4.12                           # https://pub.dev/packages/build_runner (Dart)
  flame_test: ^1.15.2                             # https://pub.dev/packages/flame_test (Flame Engine)
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0                           # https://pub.dev/packages/flutter_lints (Flutter)
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4                                 # https://pub.dev/packages/mockito (Dart)
  test: ^1.24.9                                   # https://pub.dev/packages/test (Dart)

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/sensitive.properties
    - assets/feedback_template
    - assets/fonts/
    - assets/audio/

flutter_launcher_icons:
  image_path: "../img/logo.png"
  android: true
  adaptive_icon_background: "#bb86fc"
  adaptive_icon_foreground: "../img/logo-android-adaptive.png"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#bb86fc"

flutter_native_splash:
  color: "#333333"
  android_12:
    color: "#333333"
