name: mobile
description: "A mobile tap arcade game that tests users' coordination skills."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flame: ^1.13.1          # https://pub.dev/packages/flame (Flame Engine)
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.7    # https://pub.dev/packages/build_runner (Dart)
  flame_test: ^1.15.2     # https://pub.dev/packages/flame_test (Flame Engine)
  flutter_lints: ^3.0.1   # https://pub.dev/packages/flutter_lints (Flutter)
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4         # https://pub.dev/packages/mockito (Dart)
  test: ^1.24.9           # https://pub.dev/packages/test (Dart)

flutter:
  uses-material-design: true
