name: mobile
description: "A mobile tap arcade game that tests users' coordination skills."
publish_to: "none"

version: 1.0.3+2024021601

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  collection: ^1.18.0          # https://pub.dev/packages/collection (Dart)
  flame: ^1.13.1              # https://pub.dev/packages/flame (Flame Engine)
  google_mobile_ads: ^4.0.0   # https://pub.dev/packages/google_mobile_ads (Google)
  purchases_flutter: ^6.16.1  # https://pub.dev/packages/purchases_flutter (verified)
  shared_preferences: ^2.2.2  # https://pub.dev/packages/shared_preferences (Flutter)
  url_launcher: ^6.2.4        # https://pub.dev/packages/url_launcher (Flutter)
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.7        # https://pub.dev/packages/build_runner (Dart)
  flame_test: ^1.15.2         # https://pub.dev/packages/flame_test (Flame Engine)
  flutter_lints: ^3.0.1       # https://pub.dev/packages/flutter_lints (Flutter)
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4             # https://pub.dev/packages/mockito (Dart)
  test: ^1.24.9               # https://pub.dev/packages/test (Dart)

flutter:
  uses-material-design: true

  assets:
    - assets/sensitive.properties
